version: '3.8'

x-db: &db
  platform: linux/x86_64
  image: mysql:8.0.29
  command:
    [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin",
    ]
x-dbenv: &dbenv
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_USER: admin
  MYSQL_PASSWORD: WagerService123

services:
  appdb:
    <<: *db
    volumes:
      - app_mysql:/var/lib/mysql
      # - ./deployment/dev/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      <<: *dbenv
      MYSQL_DATABASE: wager_dev

  testdb:
    <<: *db
    volumes:
      - test_mysql:/var/lib/mysql
      - ./test/docker/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 23306:3306
    environment:
      <<: *dbenv

volumes:
  app_mysql:
    driver: local
  test_mysql:
    driver: local
