development:
  dialect: mysql
  datasource: admin:wagerservice123@tcp(localhost:13306)/wager_dev?parseTime=true
  dir: migrations
  table: schema_migrations ## table contains migration info

mysql_env:
  dialect: mysql
  datasource: ${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?parseTime=true
  dir: migrations
  table: schema_migrations ## table contains migration info
